### ISSUE TITLE
Load cham 

### ISSUE THREAD

**Issue by ThanggA7** [chisphung/portfolio#1]
**Nguyên nhân:**

- Tài nguyên của m nhiều quá => web load không nhanh được 

<img width="772" alt="Ảnh màn hình 2024-03-03 lúc 03 12 07" src="https://github.com/phungminhchi2k5/portfolio/assets/59923452/c31f4f53-7e46-4530-accb-000be340271a">

(quả project portfoli 105,7 MB thì chịu =)))) )

<img width="844" alt="Ảnh màn hình 2024-03-03 lúc 03 16 13" src="https://github.com/phungminhchi2k5/portfolio/assets/59923452/7f71da53-be03-4a3e-9d78-12b7caad8c5d">
(2 thư mục img + video hơn 100MB rồi )

**Giải pháp**

- Xoá bớt tài nguyên

- Dùng thử [cái này]( https://upanh.1doi1.com/) up ảnh lấy link rồi gán vô thẻ img xem có giải quyết được không

**Comment by chisphung** [comment]
Ok
